# Mandatory settings

name: Chalkboard
paginate: 25
url: http://chalkpe.github.io
blog_theme: light

description: 다시는 반복하고 싶지 않은 끔찍한 상황들의 적절한 해결 방법을 기록해 두는 작은 블로그
copyrightYear: 2017
encoding: utf-8
timezone: Asia/Seoul

# Optional settings

about_enabled: true
discus_identifier: chalkboard-1
ga_analytics: UA-97499484-1
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true

social:
  dribbble:
  facebook:
  flickr:
  github: ChalkPE
  linkedin:
  twitter: amato17
  email: chalkpe@gmail.com
  bitcoin:

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
