title: Chalkboard
description: >
  다시는 반복하고 싶지 않은 끔찍한 상황들의
  적절한 해결 방법을 기록해 두는 작은 블로그

email: chalk@chalk.pe

timezone: Asia/Seoul
encoding: utf-8

baseurl: ""
url: "https://chalkpe.github.io"

twitter_username: amato17
github_username:  ChalkPE

disqus:
  shortname: chalkboard-1

google_analytics: UA-97499484-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
